pipeline {
    agent any

    tools {
        maven 'Maven-3'
        jdk 'JDK-21'
    }

    environment {
        EC2_HOST = "51.21.163.184"
    }

    stages {

        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target\\surefire-reports\\*.xml'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }

        stage('Deploy to EC2') {
            steps {
                withCredentials([sshUserPrivateKey(
                    credentialsId: 'ec2-key',
                    keyFileVariable: 'KEY_PATH'
                )]) {

                    bat """
                    echo ===============================
                    echo Copying JAR to EC2
                    echo ===============================

                    scp -o StrictHostKeyChecking=no -i "%KEY_PATH%" target\\*.jar ec2-user@%EC2_HOST%:/home/ec2-user/app.jar

                    echo ===============================
                    echo Deploying Application
                    echo ===============================

                    ssh -o StrictHostKeyChecking=no -i "%KEY_PATH%" ec2-user@%EC2_HOST% ^
                    "pkill -f 'java -jar' || true; nohup java -jar app.jar > app.log 2>&1 &"

                    echo ===============================
                    echo Deployment Completed
                    echo ===============================
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Deployment Failed. Check logs.'
        }
    }
}